on:
  push:
  pull_request:

env:
  BUILD_TYPE: Release
  BUILD_DIR: build

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install -y valgrind libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev lcov xvfb python3

      - name: Verify commit messages
        if: github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/master'
        run: python3 scripts/verify_commits.py

      - name: Start xvfb
        run: |
          mkdir -p /tmp/runtime-dir
          export DISPLAY=:99
          export XDG_RUNTIME_DIR=/tmp/runtime-dir
          Xvfb :99 -screen 0 1024x768x16 &
          sleep 2

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DTESTS=ON -DCLANG_TIDY=ON -DCODE_COVERAGE=ON -DENABLE_VALGRIND=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}} -j

      - name: Test
        working-directory: ${{github.workspace}}/${{env.BUILD_DIR}}
        env:
          DISPLAY: ":99"
          XDG_RUNTIME_DIR: "/tmp/runtime-dir"
        run: ctest -C ${{env.BUILD_TYPE}} --rerun-failed --output-on-failure

      - name: Code Coverage
        working-directory: ${{github.workspace}}
        run: ./scripts/coverage_html.sh gcc

      - name: Check code formatting
        run: ./scripts/check_clang_format.sh
